swagger: '2.0'
info:
  title: azure-protected-api
  x-ibm-name: azure-protected-api
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - gatewayscript:
          version: 2.0.0
          title: gatewayscript
          source: |-
            var vResults = '{"API_Invoked":"' + context.get('api.name') + '"}';

            context.set('message.body', vResults); 
            context.message.header.set('content-type', 'application/json');
    catch: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /azure-protected-api
paths:
  /:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
      security: []
    put:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
      security:
        - Azure AD OAuth:
            - resource-write
    delete:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    head:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    patch:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    parameters:
      - name: Authorization
        in: header
        type: string
securityDefinitions:
  Azure AD OAuth:
    type: oauth2
    x-ibm-oauth-provider: azuread
    flow: accessCode
    authorizationUrl: >-
      https://login.microsoftonline.com/037fbce0-c813-4c51-b804-3a0e2d34a391/oauth2/v2.0/authorize
    tokenUrl: >-
      https://login.microsoftonline.com/037fbce0-c813-4c51-b804-3a0e2d34a391/oauth2/v2.0/token
    scopes:
      resource-read: ''
      resource-write: ''
security:
  - Azure AD OAuth:
      - resource-read
      - resource-write
schemes:
  - https
